global:
  pattern: multicloud-gitops-extension
  hubClusterDomain: apps.baremetal.internal.nickday.biz

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  gitops:
    namespace: openshift-gitops
    project: hub
