apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
  name: multicloud-gitops-extension
  namespace: patterns-operator
spec:
  clusterGroupName: hub
  gitSpec:
    gitRepo: https://github.com/validatedpatterns/quarter.git
    gitBranch: feat/thin-upstream-wrapper
    path: .
  valuesFiles:
    - values-global.yaml
    - values-hub.yaml
