apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenancy-policy
  namespace: {{ include "quarter.namespaceGitops" . }}
spec:
  description: ACM tenancy policy and GUI deployment project
  sourceRepos:
    - {{ .Values.global.repositories.tenancyPolicy.repoURL | quote }}
    - {{ .Values.global.repositories.tenantGui.repoURL | quote }}
  destinations:
    - namespace: policies
      server: https://kubernetes.default.svc
    - namespace: tenancies
      server: https://kubernetes.default.svc
    - namespace: tenant-form-acm-gui
      server: https://kubernetes.default.svc
    - namespace: {{ include "quarter.namespaceGitops" . }}
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
