apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: {{ include "quarter.namespaceGitops" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  kustomizeBuildOptions: --enable-alpha-plugins
  repo:
    env:
      - name: KUSTOMIZE_PLUGIN_HOME
        value: /.config/kustomize/plugin
    initContainers:
      - name: policy-generator-install
        image: {{ .Values.global.policyGenerator.acmSubscriptionImage | quote }}
        imagePullPolicy: Always
        command:
          - /bin/bash
        args:
          - -c
          - >-
            mkdir -p /.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator &&
            cp {{ .Values.global.policyGenerator.binarySourcePath }}
            {{ .Values.global.policyGenerator.binaryTargetPath }}
        volumeMounts:
          - name: kustomize
            mountPath: /.config
    volumeMounts:
      - name: kustomize
        mountPath: /.config
    volumes:
      - name: kustomize
